# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_service_pb2 as inventory__service__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in inventory_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class InventoryServiceStub(object):
    """The inventory service definition."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductQuantity = channel.unary_unary(
            "/ordermgt.InventoryService/GetProductQuantity",
            request_serializer=inventory__service__pb2.ProductType.SerializeToString,
            response_deserializer=inventory__service__pb2.Quantity.FromString,
            _registered_method=True,
        )
        self.GetStockSummary = channel.stream_unary(
            "/ordermgt.InventoryService/GetStockSummary",
            request_serializer=inventory__service__pb2.ProductType.SerializeToString,
            response_deserializer=inventory__service__pb2.StockSummary.FromString,
            _registered_method=True,
        )


class InventoryServiceServicer(object):
    """The inventory service definition."""

    def GetProductQuantity(self, request, context):
        """Get the available quantity of a product in the warehouse"""
        ptype = request.type
        for record in self.inventories:
            if ptype == record["name"]:
                return inventory_service_pb2.Quantity(
                    amount=record["amount"], metric=record["metric"]
                )
        return inventory_service_pb2.Quantity(amount=-1, metric="items")

    def GetStockSummary(self, request_iterator, context):
        """Accepts a stream of ProductTypes, returning a StockSummary when aggregation is completed."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetProductQuantity": grpc.unary_unary_rpc_method_handler(
            servicer.GetProductQuantity,
            request_deserializer=inventory__service__pb2.ProductType.FromString,
            response_serializer=inventory__service__pb2.Quantity.SerializeToString,
        ),
        "GetStockSummary": grpc.stream_unary_rpc_method_handler(
            servicer.GetStockSummary,
            request_deserializer=inventory__service__pb2.ProductType.FromString,
            response_serializer=inventory__service__pb2.StockSummary.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ordermgt.InventoryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ordermgt.InventoryService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """The inventory service definition."""

    @staticmethod
    def GetProductQuantity(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ordermgt.InventoryService/GetProductQuantity",
            inventory__service__pb2.ProductType.SerializeToString,
            inventory__service__pb2.Quantity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStockSummary(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/ordermgt.InventoryService/GetStockSummary",
            inventory__service__pb2.ProductType.SerializeToString,
            inventory__service__pb2.StockSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
